language: java
jdk:
  - openjdk11
dist: trusty
before_install:
 - chmod +x gradlew
script:
  - gradle check
  - gradle build
after_success:
    - mkdir build
    - mv * build
    - tar -czf package.tgz build
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh