language: java
jdk:
  - oraclejdk11
dist: trusty
before_install:
 - chmod +x gradlew
 - wget https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
 - unzip -qq gradle-6.7.1-bin.zip
 - export GRADLE_HOME=$PWD/gradle-6.7.1
 - export PATH=$GRADLE_HOME/bin:$PATH
 - gradle -v
script:
  - gradle check
  - gradle build
after_success:
    - gradle jacocoTestReport coveralls
    - mkdir build
    - mv * build
    - tar -czf package.tgz build
    #- export SSHPASS=$DEPLOY_PASS
    #- sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    #- sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh