swagger: "2.0"
info:
  description: >
    fqoperation topsecret service used for performing trilateration and resolving messages from a source spacecraft.
  version: "1.0.0"
  title: "fqoperations"
  contact:
    email: "pablo.aguerre@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

paths:
  /topsecret:
    post:
      summary: trilateration and resolution of messages from source spacecraft taking into account a set of satellites. 
      operationId: topsecret
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - name: satellites composition
          in: body
          description: holder of rebel satellites
          required: true
          schema:
            $ref: '#/definitions/SatelitesComposition'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PositionHolder'
        404:
          description: Not found (unable to discover spacecraft) 
definitions:
      SatelitesComposition:
        type: object
        required: [ "satellites"]
        properties:
          satellites:
            description: set of satellites distances and messages.
            type: array
            items:
              $ref: '#/definitions/Satellite'
      Satellite:
        type: object
        required: [ "name", "distance", "message" ]
        properties:
          name:
            type: string
            description: rebel satellite name
            example: sato
          distance:
            type: number
            format: double
            description: distance between src and satellite.
            example: 142.7
          message:
            type: array
            items:
              type: string
            description: message obtained by satellite
            example: ["este", "", "un", "", ""]
      PositionHolder:
        type: object
        description: spececraft geo location and message discovered
        properties:
          position:
            $ref: '#/definitions/Position'
          message:
            type: string
            example: "este es un mensaje secreto"
      Position:
        type: object
        description: spececraft geo location discovered
        properties:
          x:
            type: number
            format: double
            example: -100.0
          y:
            type: number
            format: double
            example: 75.5

host: fqoperations.df.r.appspot.com
basePath: /v1